name: simple_testing
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/iLnaar/simple_testing

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  test: ^1.15.1

dev_dependencies:
  pedantic: ^1.9.0
